name: django-forecast-project

services:
  app:
    image: my-forecast-docker-image
    container_name: django-forecast-container
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Kolkata
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:supersecretpassword@db:5432/kharchu_db
    depends_on:
      - vite
      - redis
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kharchu_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  vite:
    image: node:22-alpine
    working_dir: /app/frontend
    command: ["sh", "-c", "npm install && npm run dev -- --host"]
    volumes:
      - .:/app
    ports:
      - "5173:5173"

  redis:
    image: redis:7-alpine
    container_name: forecast-redis
    ports:
      - "6379:6379"
    restart: always

  celery:
    image: my-forecast-docker-image
    container_name: forecast-celery
    command: celery -A budget_forecast_app worker -l info
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Kolkata
      - DATABASE_URL=postgres://postgres:supersecretpassword@db:5432/kharchu_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: always

volumes:
  postgres_data:
