# Create your models here.
from django.db import models
from django_cryptography.fields import encrypt
from django.db.models import UniqueConstraint
import uuid
import pandas as pd


class ForecastDataset(models.Model):
    """Represents a single uploaded budget file/project."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} ({self.created_at.date()})"


class HistoricalSpendManager(models.Manager):
    """Data Access Layer for Historical Spend data."""

    def get_cascading_suggestions(self, dataset_id: str, model_field: str, query: str, active_filters: dict) -> list:
        """Optimized database query to fetch unique column suggestions."""
        filter_kwargs = {"dataset_id": dataset_id}

        # Apply active cascading filters (ignore the field the user is currently typing in)
        for field, value in active_filters.items():
            if value and field != model_field:
                filter_kwargs[field] = value

        # Apply the search query
        if query:
            filter_kwargs[f"{model_field}__icontains"] = query

        # Execute optimized DB query
        suggestions = (
            self.filter(**filter_kwargs)
            .values_list(model_field, flat=True)
            .distinct()[:10]
        )
        return [str(val) for val in suggestions if val is not None]

    def get_dataset_as_dataframe(self, dataset_id: str) -> pd.DataFrame:
        """Fetches historical data and immediately returns a Pandas DataFrame."""
        historical_data = self.filter(dataset_id=dataset_id).values(
            'date', 'spend', 'account_name', 'service_name', 'bu_code', 'segment'
        )

        if not historical_data:
            raise ValueError(f"No historical data found for dataset {dataset_id}")

        return pd.DataFrame(list(historical_data))


class HistoricalSpend(models.Model):
    """Stores the actual row-by-row data from the CSV."""
    dataset = models.ForeignKey(ForecastDataset, on_delete=models.CASCADE, related_name='historical_data')
    date = models.DateField()
    spend = models.DecimalField(max_digits=14, decimal_places=2)

    # Optional granular fields based on your previous CSV structure
    account_name = models.CharField(max_length=255, null=True, blank=True)
    service_name = models.CharField(max_length=255, null=True, blank=True)
    bu_code = models.IntegerField(null=True, blank=True)
    segment = models.CharField(max_length=255, null=True, blank=True)

    # Attach the custom manager
    objects = HistoricalSpendManager()

    class Meta:
        indexes = [models.Index(fields=['dataset', 'date'])]
        constraints = [
            UniqueConstraint(
                fields=['dataset', 'date', 'service_name', 'account_name'],
                name='unique_daily_service_spend'
            )
        ]


class ForecastRun(models.Model):
    """Tracks different ML runs (and their hyperparameters) on the same dataset."""
    dataset = models.ForeignKey(ForecastDataset, on_delete=models.CASCADE, related_name='runs')
    task_id = models.CharField(max_length=255, unique=True)  # The Celery Task ID

    # Generic Model Tracking
    model_name = models.CharField(max_length=50, default="prophet")
    hyperparameters = models.JSONField(default=dict, blank=True,
                                       help_text="Stores arbitrary hyperparameters for any ML model.")

    # Results
    status = models.CharField(max_length=50, default='PENDING')
    created_at = models.DateTimeField(auto_now_add=True)
    prescriptive_insight = models.TextField(
        null=True,
        blank=True,
        help_text="FinOps AI prescriptive summary generated by Ollama - Gemma"
    )

class CloudIntegration(models.Model):
    """Stores encrypted cloud provider credentials for automated ingestion."""

    PROVIDER_CHOICES = [
        ('AWS', 'AWS Cost Explorer'),
        ('AZURE', 'Azure Cost Management'),
        ('GCP', 'Google Cloud Billing'),
    ]

    dataset = models.ForeignKey(ForecastDataset, on_delete=models.CASCADE, related_name='cloud_integrations')
    provider = models.CharField(max_length=20, choices=PROVIDER_CHOICES)
    account_id = models.CharField(max_length=255, help_text="e.g., AWS Account ID")

    # Encrypted AWS fields
    access_key = encrypt(models.CharField(max_length=255, blank=True, null=True))
    secret_key = encrypt(models.CharField(max_length=255, blank=True, null=True))
    role_arn = encrypt(models.CharField(max_length=255, blank=True, null=True))

    # Encrypted Azure specific fields (can reuse access_key for Client ID, secret_key for Client Secret)
    tenant_id = encrypt(models.CharField(max_length=255, blank=True, null=True))

    # GCP specific field
    gcp_service_account_json = encrypt(models.JSONField(blank=True, null=True))
    gcp_table_id = models.CharField(max_length=255, blank=True, null=True, help_text="project.dataset.table")

    is_active = models.BooleanField(default=True)
    last_synced_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.provider} - {self.account_id} ({self.dataset.name})"
