# Generated by Django 4.2.25 on 2026-03-22 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('changepoint_prior_scale', models.FloatField(default=0.05)),
                ('seasonality_mode', models.CharField(default='additive', max_length=50)),
                ('include_holidays', models.BooleanField(default=False)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='forecast.forecastdataset')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('spend', models.DecimalField(decimal_places=2, max_digits=14)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bu_code', models.IntegerField(blank=True, null=True)),
                ('segment', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='forecast.forecastdataset')),
            ],
            options={
                'indexes': [models.Index(fields=['dataset', 'date'], name='forecast_hi_dataset_56a628_idx')],
            },
        ),
    ]
