# Generated by Django 4.2.25 on 2026-03-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastrun',
            name='changepoint_prior_scale',
        ),
        migrations.RemoveField(
            model_name='forecastrun',
            name='include_holidays',
        ),
        migrations.RemoveField(
            model_name='forecastrun',
            name='seasonality_mode',
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='hyperparameters',
            field=models.JSONField(blank=True, default=dict, help_text='Stores arbitrary hyperparameters for any ML model.'),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='model_name',
            field=models.CharField(default='prophet', max_length=50),
        ),
    ]
