# Generated by Django 4.2.25 on 2026-04-08 09:39

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_remove_forecastrun_changepoint_prior_scale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('AWS', 'AWS Cost Explorer'), ('AZURE', 'Azure Cost Management'), ('GCP', 'Google Cloud Billing')], max_length=20)),
                ('account_id', models.CharField(help_text='e.g., AWS Account ID', max_length=255)),
                ('access_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('secret_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('role_arn', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('tenant_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('gcp_service_account_json', django_cryptography.fields.encrypt(models.JSONField(blank=True, null=True))),
                ('gcp_table_id', models.CharField(blank=True, help_text='project.dataset.table', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='historicalspend',
            constraint=models.UniqueConstraint(fields=('dataset', 'date', 'service_name', 'account_name'), name='unique_daily_service_spend'),
        ),
        migrations.AddField(
            model_name='cloudintegration',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_integrations', to='forecast.forecastdataset'),
        ),
    ]
