# Generated by Django 4.2.25 on 2026-04-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_cloudintegration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastrun',
            name='prescriptive_insight',
            field=models.TextField(blank=True, help_text='FinOps AI prescriptive summary generated by Ollama - Gemma', null=True),
        ),
    ]
